#pragma once

#define ID_BITMAP_SUN 101
#define ID_BITMAP_MERCURY 102
#define ID_BITMAP_VENUS	103
#define ID_BITMAP_EARTH 104
#define ID_BITMAP_EARTH_MOON 105
#define ID_BITMAP_MARS 106
#define ID_BITMAP_MARS_PHOBOS 107
#define ID_BITMAP_JUPITER 108
#define ID_BITMAP_JUPITER_EUROPA 109
#define ID_BITMAP_SATURN 110
#define ID_BITMAP_SATURN_TITAN 111
#define ID_BITMAP_URANUS 112
#define ID_BITMAP_URANUS_AERIAL 113
#define ID_BITMAP_NEPTUNE 114
#define ID_BITMAP_NEPTUNE_TRITON 115
#define ID_BITMAP_PLUTO 116
#define ID_BITMAP_SATURN_RING 117

